namespace xivAMP.Skin;

public static class WinampSprites
{
    private static readonly IReadOnlyDictionary<string, SkinSprite> Sprites = new Dictionary<string, SkinSprite>(StringComparer.OrdinalIgnoreCase)
    {
        ["MAIN_WINDOW_BACKGROUND"] = new("MAIN", 0, 0, 275, 116),

        ["GEN_TOP_LEFT_SELECTED"] = new("GEN", 0, 0, 25, 20),
        ["GEN_TOP_LEFT_END_SELECTED"] = new("GEN", 26, 0, 25, 20),
        ["GEN_TOP_CENTER_FILL_SELECTED"] = new("GEN", 52, 0, 25, 20),
        ["GEN_TOP_RIGHT_END_SELECTED"] = new("GEN", 78, 0, 25, 20),
        ["GEN_TOP_LEFT_RIGHT_FILL_SELECTED"] = new("GEN", 104, 0, 25, 20),
        ["GEN_TOP_RIGHT_SELECTED"] = new("GEN", 130, 0, 25, 20),
        ["GEN_TOP_LEFT"] = new("GEN", 0, 21, 25, 20),
        ["GEN_TOP_LEFT_END"] = new("GEN", 26, 21, 25, 20),
        ["GEN_TOP_CENTER_FILL"] = new("GEN", 52, 21, 25, 20),
        ["GEN_TOP_RIGHT_END"] = new("GEN", 78, 21, 25, 20),
        ["GEN_TOP_LEFT_RIGHT_FILL"] = new("GEN", 104, 21, 25, 20),
        ["GEN_TOP_RIGHT"] = new("GEN", 130, 21, 25, 20),
        ["GEN_BOTTOM_LEFT"] = new("GEN", 0, 42, 125, 14),
        ["GEN_BOTTOM_RIGHT"] = new("GEN", 0, 57, 125, 14),
        ["GEN_BOTTOM_FILL"] = new("GEN", 127, 72, 25, 14),
        ["GEN_MIDDLE_LEFT"] = new("GEN", 127, 42, 11, 29),
        ["GEN_MIDDLE_RIGHT"] = new("GEN", 139, 42, 8, 29),
        ["GEN_MIDDLE_LEFT_BOTTOM"] = new("GEN", 158, 42, 11, 24),
        ["GEN_MIDDLE_RIGHT_BOTTOM"] = new("GEN", 170, 42, 8, 24),
        ["GEN_CLOSE_SELECTED"] = new("GEN", 145, 4, 9, 9),

        ["GEN_HEADER_ACTIVE_A"] = new("GEN", 1, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_B"] = new("GEN", 8, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_C"] = new("GEN", 16, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_D"] = new("GEN", 24, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_E"] = new("GEN", 31, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_F"] = new("GEN", 38, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_G"] = new("GEN", 45, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_H"] = new("GEN", 53, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_I"] = new("GEN", 60, 88, 4, 7),
        ["GEN_HEADER_ACTIVE_J"] = new("GEN", 65, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_K"] = new("GEN", 72, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_L"] = new("GEN", 80, 88, 5, 7),
        ["GEN_HEADER_ACTIVE_M"] = new("GEN", 86, 88, 8, 7),
        ["GEN_HEADER_ACTIVE_N"] = new("GEN", 95, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_O"] = new("GEN", 102, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_P"] = new("GEN", 109, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_Q"] = new("GEN", 116, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_R"] = new("GEN", 124, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_S"] = new("GEN", 132, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_T"] = new("GEN", 139, 88, 5, 7),
        ["GEN_HEADER_ACTIVE_U"] = new("GEN", 145, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_V"] = new("GEN", 152, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_W"] = new("GEN", 159, 88, 8, 7),
        ["GEN_HEADER_ACTIVE_X"] = new("GEN", 168, 88, 7, 7),
        ["GEN_HEADER_ACTIVE_Y"] = new("GEN", 176, 88, 6, 7),
        ["GEN_HEADER_ACTIVE_Z"] = new("GEN", 183, 88, 6, 7),

        ["GEN_HEADER_INACTIVE_A"] = new("GEN", 1, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_B"] = new("GEN", 8, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_C"] = new("GEN", 16, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_D"] = new("GEN", 24, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_E"] = new("GEN", 31, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_F"] = new("GEN", 38, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_G"] = new("GEN", 45, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_H"] = new("GEN", 53, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_I"] = new("GEN", 60, 96, 4, 7),
        ["GEN_HEADER_INACTIVE_J"] = new("GEN", 65, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_K"] = new("GEN", 72, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_L"] = new("GEN", 80, 96, 5, 7),
        ["GEN_HEADER_INACTIVE_M"] = new("GEN", 86, 96, 8, 7),
        ["GEN_HEADER_INACTIVE_N"] = new("GEN", 95, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_O"] = new("GEN", 102, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_P"] = new("GEN", 109, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_Q"] = new("GEN", 116, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_R"] = new("GEN", 124, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_S"] = new("GEN", 131, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_T"] = new("GEN", 138, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_U"] = new("GEN", 145, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_V"] = new("GEN", 152, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_W"] = new("GEN", 159, 96, 8, 7),
        ["GEN_HEADER_INACTIVE_X"] = new("GEN", 168, 96, 7, 7),
        ["GEN_HEADER_INACTIVE_Y"] = new("GEN", 176, 96, 6, 7),
        ["GEN_HEADER_INACTIVE_Z"] = new("GEN", 183, 96, 6, 7),


        ["GENEX_BUTTON_ACTIVE_LEFT"] = new("GENEX", 0, 0, 3, 15),
        ["GENEX_BUTTON_ACTIVE_CENTER"] = new("GENEX", 3, 0, 1, 15),
        ["GENEX_BUTTON_ACTIVE_RIGHT"] = new("GENEX", 44, 0, 3, 15),
        ["GENEX_BUTTON_PRESSED_LEFT"] = new("GENEX", 0, 15, 3, 15),
        ["GENEX_BUTTON_PRESSED_CENTER"] = new("GENEX", 3, 15, 1, 15),
        ["GENEX_BUTTON_PRESSED_RIGHT"] = new("GENEX", 44, 15, 3, 15),
        ["GENEX_SCROLL_UP"] = new("GENEX", 0, 31, 14, 14),
        ["GENEX_SCROLL_DOWN"] = new("GENEX", 14, 31, 14, 14),
        ["GENEX_SCROLL_UP_PRESSED"] = new("GENEX", 28, 31, 14, 14),
        ["GENEX_SCROLL_DOWN_PRESSED"] = new("GENEX", 42, 31, 14, 14),
        ["GENEX_SCROLL_VERTICAL_THUMB"] = new("GENEX", 56, 31, 14, 28),
        ["GENEX_SCROLL_VERTICAL_THUMB_PRESSED"] = new("GENEX", 70, 31, 14, 28),
        ["GENEX_SCROLL_VERTICAL_BACKGROUND"] = new("GENEX", 112, 31, 14, 28),

        ["MAIN_PREVIOUS_BUTTON"] = new("CBUTTONS", 0, 0, 23, 18),
        ["MAIN_PREVIOUS_BUTTON_ACTIVE"] = new("CBUTTONS", 0, 18, 23, 18),
        ["MAIN_PLAY_BUTTON"] = new("CBUTTONS", 23, 0, 23, 18),
        ["MAIN_PLAY_BUTTON_ACTIVE"] = new("CBUTTONS", 23, 18, 23, 18),
        ["MAIN_PAUSE_BUTTON"] = new("CBUTTONS", 46, 0, 23, 18),
        ["MAIN_PAUSE_BUTTON_ACTIVE"] = new("CBUTTONS", 46, 18, 23, 18),
        ["MAIN_STOP_BUTTON"] = new("CBUTTONS", 69, 0, 23, 18),
        ["MAIN_STOP_BUTTON_ACTIVE"] = new("CBUTTONS", 69, 18, 23, 18),
        ["MAIN_NEXT_BUTTON"] = new("CBUTTONS", 92, 0, 22, 18),
        ["MAIN_NEXT_BUTTON_ACTIVE"] = new("CBUTTONS", 92, 18, 22, 18),
        ["MAIN_EJECT_BUTTON"] = new("CBUTTONS", 114, 0, 22, 16),
        ["MAIN_EJECT_BUTTON_ACTIVE"] = new("CBUTTONS", 114, 16, 22, 16),

        ["MAIN_PLAYLIST_BUTTON"] = new("SHUFREP", 23, 61, 23, 12),
        ["MAIN_PLAYLIST_BUTTON_SELECTED"] = new("SHUFREP", 23, 73, 23, 12),
        ["MAIN_PLAYLIST_BUTTON_DEPRESSED"] = new("SHUFREP", 69, 61, 23, 12),
        ["MAIN_PLAYLIST_BUTTON_DEPRESSED_SELECTED"] = new("SHUFREP", 69, 73, 23, 12),
        ["MAIN_EQ_BUTTON"] = new("SHUFREP", 0, 61, 23, 12),
        ["MAIN_EQ_BUTTON_SELECTED"] = new("SHUFREP", 0, 73, 23, 12),
        ["MAIN_EQ_BUTTON_DEPRESSED"] = new("SHUFREP", 46, 61, 23, 12),
        ["MAIN_EQ_BUTTON_DEPRESSED_SELECTED"] = new("SHUFREP", 46, 73, 23, 12),
        ["MAIN_SHUFFLE_BUTTON"] = new("SHUFREP", 28, 0, 47, 15),
        ["MAIN_SHUFFLE_BUTTON_DEPRESSED"] = new("SHUFREP", 28, 15, 47, 15),
        ["MAIN_SHUFFLE_BUTTON_SELECTED"] = new("SHUFREP", 28, 30, 47, 15),
        ["MAIN_SHUFFLE_BUTTON_SELECTED_DEPRESSED"] = new("SHUFREP", 28, 45, 47, 15),
        ["MAIN_REPEAT_BUTTON"] = new("SHUFREP", 0, 0, 28, 15),
        ["MAIN_REPEAT_BUTTON_DEPRESSED"] = new("SHUFREP", 0, 15, 28, 15),
        ["MAIN_REPEAT_BUTTON_SELECTED"] = new("SHUFREP", 0, 30, 28, 15),
        ["MAIN_REPEAT_BUTTON_SELECTED_DEPRESSED"] = new("SHUFREP", 0, 45, 28, 15),

        ["MAIN_OPTIONS_BUTTON"] = new("TITLEBAR", 0, 0, 9, 9),
        ["MAIN_OPTIONS_BUTTON_DEPRESSED"] = new("TITLEBAR", 0, 9, 9, 9),
        ["MAIN_MINIMIZE_BUTTON"] = new("TITLEBAR", 9, 0, 9, 9),
        ["MAIN_MINIMIZE_BUTTON_DEPRESSED"] = new("TITLEBAR", 9, 9, 9, 9),
        ["MAIN_CLOSE_BUTTON"] = new("TITLEBAR", 18, 0, 9, 9),
        ["MAIN_CLOSE_BUTTON_DEPRESSED"] = new("TITLEBAR", 18, 9, 9, 9),
        // Windowshade collapse button (full window) / restore button (shaded window).
        ["MAIN_SHADE_BUTTON"] = new("TITLEBAR", 0, 18, 9, 9),
        ["MAIN_SHADE_BUTTON_DEPRESSED"] = new("TITLEBAR", 9, 18, 9, 9),
        ["MAIN_UNSHADE_BUTTON"] = new("TITLEBAR", 0, 27, 9, 9),
        ["MAIN_UNSHADE_BUTTON_DEPRESSED"] = new("TITLEBAR", 9, 27, 9, 9),
        ["MAIN_TITLE_BAR"] = new("TITLEBAR", 27, 15, 275, 14),
        ["MAIN_TITLE_BAR_SELECTED"] = new("TITLEBAR", 27, 0, 275, 14),
        // Window shade mode title bars (3rd/4th rows of TITLEBAR.bmp).
        ["MAIN_SHADE_BACKGROUND_SELECTED"] = new("TITLEBAR", 27, 29, 275, 14),
        ["MAIN_SHADE_BACKGROUND"] = new("TITLEBAR", 27, 43, 275, 14),
        // Window shade mini position bar (5th row of TITLEBAR.bmp).
        ["MAIN_SHADE_POSITION_BACKGROUND"] = new("TITLEBAR", 0, 36, 17, 7),
        ["MAIN_SHADE_POSITION_THUMB"] = new("TITLEBAR", 17, 36, 10, 7),
        ["MAIN_PLAYING_INDICATOR"] = new("PLAYPAUS", 0, 0, 9, 9),
        ["MAIN_PAUSED_INDICATOR"] = new("PLAYPAUS", 9, 0, 9, 9),
        ["MAIN_STOPPED_INDICATOR"] = new("PLAYPAUS", 18, 0, 9, 9),
        ["MAIN_WORKING_INDICATOR"] = new("PLAYPAUS", 39, 0, 9, 9),
        ["MAIN_POSITION_SLIDER_BACKGROUND"] = new("POSBAR", 0, 0, 248, 10),
        ["MAIN_POSITION_SLIDER_THUMB"] = new("POSBAR", 248, 0, 29, 10),
        ["MAIN_POSITION_SLIDER_THUMB_SELECTED"] = new("POSBAR", 278, 0, 29, 10),
        ["MAIN_VOLUME_BACKGROUND"] = new("VOLUME", 0, 0, 68, 13),
        ["MAIN_VOLUME_THUMB"] = new("VOLUME", 15, 422, 14, 11),
        ["MAIN_VOLUME_THUMB_SELECTED"] = new("VOLUME", 0, 422, 14, 11),
        ["MAIN_BALANCE_BACKGROUND"] = new("BALANCE", 9, 0, 38, 13),
        ["MAIN_BALANCE_THUMB"] = new("BALANCE", 15, 422, 14, 11),
        ["MAIN_BALANCE_THUMB_ACTIVE"] = new("BALANCE", 0, 422, 14, 11),
        ["MAIN_STEREO"] = new("MONOSTER", 0, 12, 29, 12),
        ["MAIN_STEREO_SELECTED"] = new("MONOSTER", 0, 0, 29, 12),
        ["MAIN_MONO"] = new("MONOSTER", 29, 12, 27, 12),
        ["MAIN_MONO_SELECTED"] = new("MONOSTER", 29, 0, 27, 12),

        ["PLAYLIST_TOP_TILE"] = new("PLEDIT", 127, 0, 25, 20),
        ["PLAYLIST_TOP_LEFT_CORNER"] = new("PLEDIT", 0, 0, 25, 20),
        ["PLAYLIST_TITLE_BAR"] = new("PLEDIT", 26, 0, 100, 20),
        ["PLAYLIST_TOP_RIGHT_CORNER"] = new("PLEDIT", 153, 0, 25, 20),
        ["PLAYLIST_TOP_TILE_SELECTED"] = new("PLEDIT", 127, 0, 25, 20),
        ["PLAYLIST_TOP_LEFT_SELECTED"] = new("PLEDIT", 0, 0, 25, 20),
        ["PLAYLIST_TITLE_BAR_SELECTED"] = new("PLEDIT", 26, 0, 100, 20),
        ["PLAYLIST_TOP_RIGHT_CORNER_SELECTED"] = new("PLEDIT", 153, 0, 25, 20),
        ["PLAYLIST_LEFT_TILE"] = new("PLEDIT", 0, 42, 12, 29),
        ["PLAYLIST_RIGHT_TILE"] = new("PLEDIT", 31, 42, 20, 29),
        ["PLAYLIST_BOTTOM_TILE"] = new("PLEDIT", 179, 0, 25, 38),
        ["PLAYLIST_BOTTOM_LEFT_CORNER"] = new("PLEDIT", 0, 72, 125, 38),
        ["PLAYLIST_BOTTOM_RIGHT_CORNER"] = new("PLEDIT", 126, 72, 150, 38),
        ["PLAYLIST_CLOSE_SELECTED"] = new("PLEDIT", 168, 4, 9, 9),
        ["PLAYLIST_COLLAPSE_SELECTED"] = new("PLEDIT", 158, 4, 9, 9),

        // Playlist windowshade title bar: fixed left cap, stretchable middle, fixed
        // right cap (bakes the mini scrollbar + collapse + close buttons).
        ["PLAYLIST_SHADE_LEFT"] = new("PLEDIT", 72, 42, 25, 14),
        ["PLAYLIST_SHADE_MIDDLE"] = new("PLEDIT", 72, 57, 25, 14),
        ["PLAYLIST_SHADE_RIGHT"] = new("PLEDIT", 99, 42, 50, 14),
        ["PLAYLIST_SCROLLBAR_HANDLE"] = new("PLEDIT", 52, 53, 8, 18),
        ["PLAYLIST_SCROLLBAR_HANDLE_ACTIVE"] = new("PLEDIT", 61, 53, 8, 18),

        // REM menu column in PLEDIT.BMP (top→bottom): REM ALL (111), CROP (130),
        // REM SEL (149), REM MISC (168). Pressed variants at x=77. Sidebar bar at x=100 (3x72).
        ["PLAYLIST_REM_ALL"] = new("PLEDIT", 54, 111, 22, 18),
        ["PLAYLIST_REM_ALL_PRESSED"] = new("PLEDIT", 77, 111, 22, 18),
        ["PLAYLIST_REM_CROP"] = new("PLEDIT", 54, 130, 22, 18),
        ["PLAYLIST_REM_CROP_PRESSED"] = new("PLEDIT", 77, 130, 22, 18),
        ["PLAYLIST_REM_SEL"] = new("PLEDIT", 54, 149, 22, 18),
        ["PLAYLIST_REM_SEL_PRESSED"] = new("PLEDIT", 77, 149, 22, 18),
        ["PLAYLIST_REM_SIDEBAR"] = new("PLEDIT", 100, 111, 3, 54),



    };

    public static bool TryGet(string name, out SkinSprite sprite)
        => Sprites.TryGetValue(name, out sprite);
}
